export interface GameplayTuning {
  mouthOpenThreshold: number;
  mouthRadius: number;
  trackingMaxDistance: number;
  trackingLostGraceFrames: number;
  trackingMergeDistance: number;
  trackingCandidateMergeDistance: number;
  trackingCandidateMinDistance: number;
  trackingNewPlayerFrames: number;
  trackingCandidateMaxAge: number;
  hungerBaseDecay: number;
  hungerLevelDecay: number;
  levelScoreStep: number;
  spawnBaseInterval: number;
  spawnMinInterval: number;
  spawnLevelSpeedup: number;
  spawnPlayerFactor: number;
  feverFrames: number;
  shieldFrames: number;
  maskFrames: number;
  sunglassesFrames: number;
  healthyStreakForSunglasses: number;
  kissCooldownFrames: number;
  stormIntervalFrames: number;
  stormDurationFrames: number;
  stormSpawnMultiplier: number;
  stormScoreMultiplier: number;
  matchDurationFrames: number;
  endgameDurationFrames: number;
  endgameScoreMultiplier: number;
  endgameTrapWeightMultiplier: number;
  powerupSlowFrames: number;
  powerupMagnetFrames: number;
  powerupReflectFrames: number;
  powerupMagnetMultiplier: number;
  powerupSlowFallMultiplier: number;
  comboScoreBoostFrames: number;
  comboScoreBoostMultiplier: number;
  comboShieldFrames: number;
  comboFeverFrames: number;
  audienceIntervalFrames: number;
  audienceQuakeFrames: number;
  audienceSugarBoost: number;
  dizzyFrames: number;
  poopStormFrames: number;
  trapFlashFrames: number;
  bombShakeFrames: number;
  surpriseIntervalFrames: number;
  surpriseDurationFrames: number;
  surpriseScareFrames: number;
  surpriseFreezeFrames: number;
  surpriseGoldenMultiplier: number;
  surpriseTrapMultiplier: number;
  dropSpeedMultiplier: number;
}

export const TUNING: GameplayTuning = {
  mouthOpenThreshold: 0.05,
  mouthRadius: 50,
  trackingMaxDistance: 0.2,
  trackingLostGraceFrames: 18,
  trackingMergeDistance: 0.06,
  trackingCandidateMergeDistance: 0.08,
  trackingCandidateMinDistance: 0.12,
  trackingNewPlayerFrames: 12,
  trackingCandidateMaxAge: 30,
  hungerBaseDecay: 0.06,
  hungerLevelDecay: 0.012,
  levelScoreStep: 1200,
  spawnBaseInterval: 52,
  spawnMinInterval: 9,
  spawnLevelSpeedup: 3,
  spawnPlayerFactor: 0.25,
  feverFrames: 240,
  shieldFrames: 180,
  maskFrames: 120,
  sunglassesFrames: 240,
  healthyStreakForSunglasses: 3,
  kissCooldownFrames: 90,
  stormIntervalFrames: 1800,
  stormDurationFrames: 300,
  stormSpawnMultiplier: 0.6,
  stormScoreMultiplier: 1.5,
  matchDurationFrames: 10800,
  endgameDurationFrames: 600,
  endgameScoreMultiplier: 2,
  endgameTrapWeightMultiplier: 1.6,
  powerupSlowFrames: 240,
  powerupMagnetFrames: 240,
  powerupReflectFrames: 240,
  powerupMagnetMultiplier: 1.35,
  powerupSlowFallMultiplier: 0.55,
  comboScoreBoostFrames: 300,
  comboScoreBoostMultiplier: 1.1,
  comboShieldFrames: 120,
  comboFeverFrames: 180,
  audienceIntervalFrames: 600,
  audienceQuakeFrames: 90,
  audienceSugarBoost: 20,
  dizzyFrames: 180,
  poopStormFrames: 180,
  trapFlashFrames: 18,
  bombShakeFrames: 22,
  surpriseIntervalFrames: 1200,
  surpriseDurationFrames: 180,
  surpriseScareFrames: 120,
  surpriseFreezeFrames: 90,
  surpriseGoldenMultiplier: 4,
  surpriseTrapMultiplier: 1.5,
  dropSpeedMultiplier: 1.25
};
